### ISSUE TITLE
Spring Transaction

### ISSUE THREAD

**Issue by raycon** [raycon/til#96]
https://www.baeldung.com/transaction-configuration-with-jpa-and-spring

```yml
logging:
  level:
    org:
      springframework:
        transctaion: trace
```

**Comment by raycon** [comment]
```yml
---
# Debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        transaction: error
      hibernate:
        type:
          descriptor:
            sql: trace

```
